export const Product = "products/fetchSuccess"
export const Keyboard = "keyboard/fetchSuccess"
export const Headset = "headset/fetchSuccess"
export const Webcam = "webcam/fetchSuccess"
export const products_loading = "products/loading"
export const keyboards_loading = "keyboards/loading"
export const webcam_loading = "webcam/loading"
export const headset_loading = "headset/loading"
export const BASE_URL = "http://localhost:3000"

export const headsetDetail_loading = "headsetdetail/loading"
export const HeadsetDetail = "headsetdetail/fetchSuccess"
export const keyboardDetail_loading = "keyboarddetail/loading"
export const KeyboardDetail = "keyboarddetail/fetchSuccess"
export const WebcamDetail = "webcamdetail/fetchSuccess"
export const webcamDetail_loading = "webcamdetail/loading"
